trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: KafkaDeployment
  displayName: KafkaDeployment
  jobs:
  - deployment: KafkaDeployment
    displayName: KafkaDeployment
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                kubectl get namespace memcached --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster || kubectl create namespace memcached --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl label ns kafka istio-injection=enabled --overwrite --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                yes|argocd login argocd.singhritesh85.com --username admin --password $(ARGOCD_PASSWORD) --grpc-web --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                argocd repo add https://github.com/singhritesh85/helm-repo-for-bitnami-kafka.git --username $(GITHUB_USERNAME) --password $(GITHUB_PASSWORD) --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                argocd app create kafka-with-kraft --project default --repo https://github.com/singhritesh85/helm-repo-for-bitnami-kafka.git --path ./ --dest-namespace kafka --sync-option CreateNamespace=true --dest-server https://kubernetes.default.svc --helm-set kraft.enabled=true --helm-set zookeeper.enabled=false --helm-set controller.replicaCount=3 --helm-set controller.persistence.enabled=true --helm-set controller.persistence.size=1Gi --helm-set controller.persistence.storageClass=standard-rwo --helm-set broker.replicaCount=3 --helm-set broker.persistence.storageClass=standard-rwo --helm-set broker.persistence.enabled=true --helm-set broker.persistence.size=1Gi --helm-set controller.resources.limits.cpu=500m --helm-set controller.resources.requests.cpu=250m --helm-set controller.resources.limits.memory=512Mi --helm-set controller.resources.requests.memory=256Mi --helm-set broker.resources.limits.cpu=500m --helm-set broker.resources.requests.cpu=250m --helm-set broker.resources.limits.memory=512Mi --helm-set broker.resources.requests.memory=256Mi --helm-set listeners.client.protocol=PLAINTEXT --helm-set listeners.controller.protocol=PLAINTEXT --helm-set listeners.interbroker.protocol=PLAINTEXT --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster --upsert
                argocd app sync kafka-with-kraft --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                kubectl get pods -n kafka-with-kraft --context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster

          