trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: PostgreSQLDeployment
  displayName: PostgreSQLDeployment
  jobs:
  - deployment: PostgreSQLDeployment
    displayName: PostgreSQLDeployment
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                "yes|argocd login argocd.singhritesh85.com --username admin --password ${ARGOCD_PASSWORD} --grpc-web"
                argocd repo add https://github.com/singhritesh85/helm-repo-for-bitnami-postgresql-ha.git --username ${GITHUB_USERNAME} --password ${GITHUB_PASSWORD}
                argocd app create postgresql --project default --repo https://github.com/singhritesh85/helm-repo-for-bitnami-postgresql-primary-secondary.git --path ./bitnami/postgresql-ha --dest-namespace postgresql --sync-option CreateNamespace=true --dest-server https://kubernetes.default.svc --helm-set architecture=replication,auth.secretKeys.replicationPasswordKey=replication-password,readReplicas.replicaCount=3,primary.persistence.enabled=true,readReplicas.persistence.enabled=true,primary.persistence.size=1Gi,readReplicas.persistence.size=1Gi,global.storageClass=managed-csi,primary.service.type=ClusterIP,serviceAccount.create=false,serviceAccount.name=postgres-sa,primary.extraVolumes[0].name=secrets-store-inline,primary.extraVolumes[0].csi.driver="secrets-store.csi.k8s.io",primary.extraVolumes[0].csi.readOnly=true,primary.extraVolumes[0].csi.volumeAttributes.secretProviderClass=azure-kv-secrets,primary.extraVolumeMounts[0].name=secrets-store-inline,primary.extraVolumeMounts[0].mountPath=/mnt/secrets-store,primary.extraVolumeMounts[0].readOnly=true,readReplicas.extraVolumes[0].name=secrets-store-inline,readReplicas.extraVolumes[0].csi.driver="secrets-store.csi.k8s.io",readReplicas.extraVolumes[0].csi.readOnly=true,readReplicas.extraVolumes[0].csi.volumeAttributes.secretProviderClass=azure-kv-secrets,readReplicas.extraVolumeMounts[0].name=secrets-store-inline,readReplicas.extraVolumeMounts[0].mountPath=/mnt/secrets-store,readReplicas.extraVolumeMounts[0].readOnly=true,auth.existingSecret=db-credentials,global.postgresql.auth.username=dexter,auth.userPasswordKey=password,global.postgresql.auth.database=mederma  --kube-context=multicloud-aks-cluster --upsert
                argocd app sync postgresql --kube-context=multicloud-aks-cluster
                
          