trigger:
- none

pool: 
  name: demo
  demands:
  - agent.name -equals demo

stages:
- stage: PostgreSQLDeployment
  displayName: PostgreSQLDeployment
  jobs:
  - deployment: PostgreSQLDeployment
    displayName: PostgreSQLDeployment
    environment: "dev"
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          - task: CmdLine@2
            inputs:
              script: |
                yes|argocd login argocd.singhritesh85.com --username admin --password $(ARGOCD_PASSWORD) --grpc-web --kube-context=gke_wise-trainer-244916_us-central1_multicloud-gke-cluster
                argocd repo add https://github.com/singhritesh85/helm-repo-for-bitnami-postgresql-primary-secondary.git --username $(GITHUB_USERNAME) --password $(GITHUB_PASSWORD)
                argocd app create postgresql --project default --repo https://github.com/singhritesh85/helm-repo-for-bitnami-postgresql-primary-secondary.git --path ./ --dest-namespace postgresql --sync-option CreateNamespace=true --dest-server https://multicloud-cluster-dns-y63o436m.hcp.eastus.azmk8s.io:443 --helm-set architecture=replication --helm-set auth.secretKeys.replicationPasswordKey=replication-password --helm-set readReplicas.replicaCount=3 --helm-set primary.persistence.enabled=true --helm-set readReplicas.persistence.enabled=true --helm-set primary.persistence.size=1Gi --helm-set readReplicas.persistence.size=1Gi --helm-set global.storageClass=managed-csi --helm-set primary.service.type=ClusterIP --helm-set serviceAccount.create=false --helm-set serviceAccount.name=postgres-sa --helm-set primary.extraVolumes[0].name=secrets-store-inline --helm-set primary.extraVolumes[0].csi.driver="secrets-store.csi.k8s.io" --helm-set primary.extraVolumes[0].csi.readOnly=true --helm-set primary.extraVolumes[0].csi.volumeAttributes.secretProviderClass=azure-kv-secrets --helm-set primary.extraVolumeMounts[0].name=secrets-store-inline --helm-set primary.extraVolumeMounts[0].mountPath=/mnt/secrets-store --helm-set primary.extraVolumeMounts[0].readOnly=true --helm-set readReplicas.extraVolumes[0].name=secrets-store-inline --helm-set readReplicas.extraVolumes[0].csi.driver="secrets-store.csi.k8s.io" --helm-set readReplicas.extraVolumes[0].csi.readOnly=true --helm-set readReplicas.extraVolumes[0].csi.volumeAttributes.secretProviderClass=azure-kv-secrets --helm-set readReplicas.extraVolumeMounts[0].name=secrets-store-inline --helm-set readReplicas.extraVolumeMounts[0].mountPath=/mnt/secrets-store --helm-set readReplicas.extraVolumeMounts[0].readOnly=true --helm-set auth.existingSecret=db-credentials --helm-set global.postgresql.auth.username=dexter --helm-set auth.userPasswordKey=password --helm-set global.postgresql.auth.database=mederma  --kube-context=multicloud-aks-cluster --upsert
                argocd app sync postgresql --kube-context=multicloud-aks-cluster
                
          